### PR TITLE
fixes #29 - If google is already loaded, don't try to load it again

### LINKED ISSUE #29: Using vuetify-google-autocomplete with vue-google-maps
Hi @MadimetjaShika,

I'm building a Vue component using vuetify-google-autocomplete and [vue-google-maps](https://github.com/xkjyeah/vue-google-maps).
It seems I'm running into trouble as both access the Google Maps API as you suspected in #16:
> As noted on the release notes, you might still experience issues if you try to use this component with a different vue component that also loads the Google API. I haven't yet built to cater for that.

I tried using `:load-google-api` as mentioned in the release notes, without success.

Do you have plans in the near future to make such an integration possible? If not, do you know if there is a workaround?

**Edit:**
To give you a bit more information and context, the app is using vue-router.
vue-google-maps is initialized globally (`Vue.use(...)` in main.js) while vuetify-google-autocomplete is initialized locally as a component.
I've noticed that when navigating (using vue-router) from a page that does not include vuetify-google-autocomplete to a page that includes it makes it work properly. Accessing the page directly causes vuetify-google-autocomplete to fail silently. In both cases, vue-google-maps works properly.

Thanks,
Jonathan

### PR DESCRIPTION
**Pull request by gabaum10**
If google is loaded, but doesn't contain the necessary places API, then it'll throw an error.

### CODE REVIEW

**Comment by gabaum10** [comment]
Crap, I committed that last change on the wrong branch.  One sec, need to revert.

**Comment by gabaum10** [comment]
@MadimetjaShika I seem to have messed up the PRs linked here.  There are really only two changes I wanted to suggest 17701c96121c830795816bd9d605a190335bc2b9 and 6cb88cd2c5f9739199decf00657b6b42473bf1d .   I apologize for the confusion, I'm not super experienced with external PRs.

**Comment by gabaum10** [comment]
ALso, I have no idea why those builds are failing.  It looks like it's failing on NPM install...

**Comment by gabaum10** [comment]
If you want, we can delete the pull request, I'll make new branches and cherry pick the changes in and then resubmit them independently.  Let me know how you want to proceed.

**Review by MadimetjaShika — APPROVED** [review]
LGTM - Nice work!

I think line 449 of VuetifyGoogleAutocomplete.js should be okay.. As far as i've seen it doesn't break anything else. It would be great if I had tests sorted out for this library... But thanks!

**Pull request merged**
